### ISSUE TITLE
Remove devtools-saas branch

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/booster-catalog#56]
As of in https://github.com/openshiftio/appdev-planning/issues/30, the `devtools-saas` branch can be safely removed

**Comment by gastaldi** [comment]
@jstrachan I need your OK in this issue to proceed

**Comment by jstrachan** [comment]
@gastaldi please go ahead, we are on 'next' now

**Comment by gastaldi** [comment]
Branch deleted. Thanks!
